// Builds lib/words.js from the SUBTLEX-US spoken-English frequency list (subtlex-word-frequencies,
// ISC). Words are lowercased, letters only, most common first. Run: node scripts/build-words.mjs [index.json]
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const LIMIT = 60000;
const source = process.argv[2] ?? createRequire(import.meta.url).resolve("subtlex-word-frequencies/index.json");
const seen = new Set();
for (const { word } of JSON.parse(readFileSync(source, "utf8"))) {
  const w = word.toLowerCase();
  if (!/^[a-z]+$/.test(w) || seen.has(w)) continue;
  if (w.length === 1 && w !== "a" && w !== "i") continue; // "s", "t" come from split contractions
  seen.add(w);
  if (seen.size === LIMIT) break;
}
const out = new URL("../lib/words.js", import.meta.url);
writeFileSync(
  out,
  `// Generated by scripts/build-words.mjs from SUBTLEX-US (subtlex-word-frequencies, ISC). Most common first.\nexport default ${JSON.stringify([...seen].join(" "))};\n`,
);
console.log(`${seen.size} words → lib/words.js`);
